# Generated by Django 2.2.3 on 2019-07-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('tag', models.CharField(default='', max_length=200)),
                ('text', models.TextField()),
                ('photo_main', models.ImageField(upload_to='photos')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authors.Author')),
            ],
        ),
    ]
