# Generated by Django 2.2.3 on 2019-07-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190722_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=200)),
                ('Symbol', models.CharField(max_length=10)),
                ('CurrentPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PercentChange', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
