# Generated by Django 2.2.3 on 2019-07-23 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_quotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='StockQuotes',
        ),
    ]
