# Generated by Django 2.2.3 on 2019-07-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article'),
            preserve_default=False,
        ),
    ]
