# Generated by Django 2.2.3 on 2019-07-24 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comments_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='article',
            name='promo',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
