# Generated by Django 2.2.3 on 2019-07-24 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_comments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disclosure',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
