# Generated by Django 2.2.3 on 2019-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_disclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='disclosure',
            field=models.TextField(),
        ),
    ]
