# Generated by Django 2.2.3 on 2019-07-24 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo_main',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos'),
            preserve_default=False,
        ),
    ]
